name: Plane Wrangler CI-CD

on:
  push:
    branches: [main]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: Dockerfile
      PROJECT: Application/Application.csproj
      APPSETTINGS: Application/appsettings.json
      REPLACESETTINGS: Application/Deployment/appsettings.Production.json
      TAG: interplanewrangler
    steps:
     - uses: actions/checkout@v2
     - 
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["${{env.REPLACESETTINGS}}"]'
      env:
        RABBIT_PASSWORD : ${{secrets.RABBIT_PASSWORD}}
        ONPREM_REDIS : ${{secrets.ONPREM_REDIS}}
        INFLUXDB_TOKEN : ${{secrets.INFLUXDB_TOKEN}}
     - 
      name: Replace Appsettings
      run: cp ${{env.REPLACESETTINGS}} ${{env.APPSETTINGS}}
     - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
     - 
      name: Restore dependencies
      run: dotnet restore
     - 
      name: Build
      run: dotnet build --no-restore
     - 
      name: Publish
      run: dotnet publish -c Release -o ./app
     - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ${{secrets.DOCKER_HOST}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
     - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ${{env.WORKDIR}}/Dockerfile
        push: true
        tags: |
          ${{secrets.DOCKER_HOST}}/${{env.TAG}}
  deploy:
    needs: build-publish
    runs-on: ubuntu-latest
    env:
      TAG: interplanewrangler
    steps:
    - 
      name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command:  docker pull ${{secrets.DOCKER_HOST}}/${{env.TAG}}; docker stop ${{env.TAG}}; docker rm ${{env.TAG}}; docker run --name ${{env.TAG}} --restart=unless-stopped --net inter-network --m=100m --dns=10.0.0.33 -d ${{secrets.DOCKER_HOST}}/${{env.TAG}}; 
        host: ${{secrets.HOST}}
        username: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
