name: Plane Wrangler CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: Dockerfile
      PROJECT: Application/Application.csproj
      APPSETTINGS: Application/appsettings.json
      REPLACESETTINGS: Application/Deployment/appsettings.Production.json
      TAG: interplanewranglenet8
    steps:
     - uses: actions/checkout@v2
     - name: files-ls
  # You may pin to the exact commit or the version.
  # uses: sigyl-actions/files-ls@750629debc5b5eb3f651b1d44862cbdd19fb1d70
       uses: sigyl-actions/files-ls@v0.0.1
       with:
        folder: "/"      
     - 
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["${{env.REPLACESETTINGS}}"]'
      env:
        RABBIT_PASSWORD : ${{secrets.RABBIT_PASSWORD}}
        ONPREM_REDIS : ${{secrets.ONPREM_REDIS}}
        INFLUXDB_TOKEN : ${{secrets.INFLUXDB_TOKEN}}
     - 
      name: Replace Appsettings
      run: cp ${{env.REPLACESETTINGS}} ${{env.APPSETTINGS}}
     - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
     - 
      name: Restore dependencies
      run: dotnet restore
     - 
      name: Build
      run: dotnet build --no-restore
     - 
      name: Publish
      run: dotnet publish -c Release -o ./app
     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
        registry: ${{secrets.DOCKER_HOST}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}      
     - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
       uses: docker/build-push-action@v5.1.0
       with:
            context: ./
            file: Dockerfile
            push: true
            tags: |
              ${{secrets.DOCKER_HOST}}/${{env.TAG}}
  deploy:
    needs: build-publish
    runs-on: ubuntu-latest
    env:
      TAG: interplanewranglenet8
    steps:
     - name: SSH Command
    # uses: nekiro/ssh-job@e0d177751aced5bcaf110ce4d782a681e5e12856
       uses: nekiro/ssh-job@v1.0.5
       with:
        command:  docker pull ${{secrets.DOCKER_HOST}}/${{env.TAG}}; docker stop ${{env.TAG}}; docker rm ${{env.TAG}}; docker run --name ${{env.TAG}} --restart=unless-stopped -p 8081:8080 --net inter_network -m=500m -d ${{secrets.DOCKER_HOST}}/${{env.TAG}}; 
        host: ${{secrets.HOST}}
        user: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
